// AUTO-GENERATED from .tmp/kw.json (真实关键词库 176 词). 勿手改；改数据请重跑 scripts/_gen-all-keywords.ts。
import type { RawKeyword } from "./_workbench";

export const ALL_KEYWORDS: RawKeyword[] = [
  { id: "k0", keyword: "dzikir", market: "id", sv: 40500, kd: 32, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k1", keyword: "abaya", market: "us", sv: 33100, kd: 40, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k2", keyword: "slow living", market: "id", sv: 22200, kd: 28, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k3", keyword: "nominal", market: "id", sv: 12100, kd: 21, intent: null, behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k4", keyword: "bracelet", market: "my", sv: 8100, kd: 21, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k5", keyword: "necklace", market: "my", sv: 6600, kd: 19, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k6", keyword: "prayer mat", market: "us", sv: 5400, kd: 21, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k7", keyword: "eid gifts", market: "uk", sv: 4400, kd: 16, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k8", keyword: "tasbih", market: "us", sv: 3600, kd: 35, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k9", keyword: "tasbih", market: "fr", sv: 3600, kd: 17, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k10", keyword: "hand chain", market: "my", sv: 3600, kd: 9, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k11", keyword: "azan ke baad ki dua", market: "sa", sv: 2900, kd: 26, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k12", keyword: "bow earrings", market: "my", sv: 2900, kd: 12, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k13", keyword: "gold name necklace", market: "uk", sv: 2900, kd: 11, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k14", keyword: "why do muslim women wear hijabs", market: "us", sv: 2900, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "why" },
  { id: "k15", keyword: "bracelets for women", market: "id", sv: 2900, kd: 23, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k16", keyword: "tasbih", market: "uk", sv: 2400, kd: 22, intent: "Commercial", behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k17", keyword: "umrah mubarak gifts", market: "uk", sv: 2400, kd: 5, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k18", keyword: "gifts of ramadan", market: "uk", sv: 2400, kd: 17, intent: "Informational", behaviorIntent: "混合型", pagePlanningIntent: "场景使用页", layer: "四级兜底", questionType: null },
  { id: "k19", keyword: "tasbeeh counter", market: "my", sv: 2400, kd: 25, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "一级核心", questionType: null },
  { id: "k20", keyword: "bracelet for women", market: "id", sv: 1900, kd: 16, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k21", keyword: "what is a hijab", market: "us", sv: 1900, kd: 28, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k22", keyword: "qiblah finder", market: "my", sv: 1900, kd: 0, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k23", keyword: "ladies gold earrings", market: "my", sv: 1900, kd: 10, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k24", keyword: "kaaba compass", market: "my", sv: 1900, kd: 27, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k25", keyword: "mens necklaces", market: "my", sv: 1900, kd: 13, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k26", keyword: "kaaba direction", market: "ae", sv: 1900, kd: 29, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k27", keyword: "qibla compass", market: "my", sv: 1900, kd: 33, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k28", keyword: "how to pray janazah prayer", market: "sa", sv: 1600, kd: 6, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k29", keyword: "ramadan gifts", market: "uk", sv: 1600, kd: 16, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k30", keyword: "aisha's charms", market: "my", sv: 1600, kd: 19, intent: null, behaviorIntent: "官网导航", pagePlanningIntent: "品牌主页", layer: "二级独立", questionType: null },
  { id: "k31", keyword: "hoop earrings", market: "my", sv: 1600, kd: 15, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k32", keyword: "nose ring", market: "sa", sv: 1600, kd: 21, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k33", keyword: "tasbih", market: "de", sv: 1300, kd: 32, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k34", keyword: "tasbih digital counter", market: "my", sv: 1300, kd: 26, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "一级核心", questionType: null },
  { id: "k35", keyword: "islam present", market: "uk", sv: 1300, kd: 7, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k36", keyword: "eid presents", market: "uk", sv: 1300, kd: 20, intent: "Informational", behaviorIntent: "混合型", pagePlanningIntent: "场景使用页", layer: "四级兜底", questionType: null },
  { id: "k37", keyword: "نقل عفش بالرياض باكستاني", market: "sa", sv: 1300, kd: 14, intent: null, behaviorIntent: "线下到访", pagePlanningIntent: "门店页", layer: "二级独立", questionType: null },
  { id: "k38", keyword: "gifts islam", market: "uk", sv: 1300, kd: 22, intent: "Informational", behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k39", keyword: "necklace for women", market: "id", sv: 1300, kd: 17, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k40", keyword: "prayer times", market: "us", sv: 1200, kd: 21, intent: "Navigational", behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k41", keyword: "islamic gifts", market: "uk", sv: 1000, kd: 36, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k42", keyword: "prayer mat praying", market: "id", sv: 1000, kd: 5, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k43", keyword: "tasbih", market: "sa", sv: 1000, kd: 27, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k44", keyword: "umrah gifts", market: "uk", sv: 1000, kd: 12, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k45", keyword: "tasbih", market: "sa", sv: 1000, kd: 27, intent: "Informational", behaviorIntent: "混合型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k46", keyword: "prayer rug", market: "id", sv: 880, kd: 12, intent: null, behaviorIntent: "了解型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k47", keyword: "anklet", market: "sa", sv: 880, kd: 14, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k48", keyword: "qibla finder online", market: "my", sv: 880, kd: 37, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k49", keyword: "tasbih", market: "ae", sv: 880, kd: 36, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k50", keyword: "aqeeq stone", market: "sa", sv: 880, kd: 17, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k51", keyword: "zikr ring counter", market: "us", sv: 820, kd: 38, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k52", keyword: "qiblah fonder", market: "my", sv: 720, kd: 40, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k53", keyword: "apa itu tasbih", market: "my", sv: 720, kd: 22, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k54", keyword: "apa itu tasbih", market: "uk", sv: 720, kd: 22, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k55", keyword: "solat tasbih", market: "sa", sv: 720, kd: 14, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k56", keyword: "خاتم ذكي", market: "sa", sv: 720, kd: 22, intent: null, behaviorIntent: "了解型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k57", keyword: "apa itu tasbih", market: "ae", sv: 720, kd: 22, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k58", keyword: "tasbeeh", market: "sa", sv: 720, kd: 24, intent: "Informational", behaviorIntent: "混合型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k59", keyword: "apa itu tasbih", market: "id", sv: 720, kd: 22, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k60", keyword: "gifts islamic", market: "uk", sv: 720, kd: 32, intent: "Commercial", behaviorIntent: "对比型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k61", keyword: "night routine", market: "id", sv: 720, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k62", keyword: "sholat tasbih", market: "sa", sv: 720, kd: 27, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k63", keyword: "ramadan gift ideas", market: "uk", sv: 720, kd: 25, intent: "Informational", behaviorIntent: "对比型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k64", keyword: "apa itu sholat tasbih", market: "uk", sv: 590, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k65", keyword: "gift ramadan", market: "uk", sv: 590, kd: 13, intent: "Informational", behaviorIntent: "对比型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k66", keyword: "how to pray salatul tasbih prayer", market: "uk", sv: 590, kd: 8, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k67", keyword: "zikr after namaz", market: "uk", sv: 590, kd: 11, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k68", keyword: "apa itu sholat tasbih", market: "ae", sv: 590, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k69", keyword: "hand chain", market: "sa", sv: 590, kd: 12, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k70", keyword: "slow living", market: "uk", sv: 590, kd: 28, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k71", keyword: "which way is mecca", market: "id", sv: 590, kd: 31, intent: null, behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k72", keyword: "how to do salatul tasbih", market: "uk", sv: 590, kd: 8, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k73", keyword: "apa itu sholat tasbih", market: "id", sv: 590, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k74", keyword: "how to salatul tasbih prayer", market: "uk", sv: 590, kd: 7, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k75", keyword: "apa itu sholat tasbih", market: "my", sv: 590, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k76", keyword: "dhikr after namaz", market: "uk", sv: 480, kd: 12, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k77", keyword: "zikr after prayer", market: "uk", sv: 480, kd: 15, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k78", keyword: "zikr ring", market: "uk", sv: 480, kd: 16, intent: "Informational", behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k79", keyword: "salam occasions", market: "uk", sv: 480, kd: 16, intent: "Navigational", behaviorIntent: "官网导航", pagePlanningIntent: "品牌主页", layer: "一级核心", questionType: null },
  { id: "k80", keyword: "zikr ring", market: "id", sv: 480, kd: 16, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k81", keyword: "zikr ring", market: "my", sv: 480, kd: 16, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k82", keyword: "kaba direction", market: "id", sv: 480, kd: 34, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k83", keyword: "gold name necklace", market: "ae", sv: 480, kd: 6, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k84", keyword: "tasbih prayer", market: "sa", sv: 390, kd: 16, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k85", keyword: "apa arti tasbih", market: "id", sv: 390, kd: 24, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k86", keyword: "نقل عفش باكستاني", market: "sa", sv: 390, kd: 14, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "产品详情页", layer: "二级独立", questionType: null },
  { id: "k87", keyword: "salat tasbeeh", market: "sa", sv: 390, kd: 17, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k88", keyword: "smart watch for kids", market: "sa", sv: 390, kd: 19, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k89", keyword: "islamic wedding gifts", market: "uk", sv: 390, kd: 17, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k90", keyword: "dhikr after salah", market: "uk", sv: 390, kd: 11, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k91", keyword: "kapan sholat tasbih dilakukan", market: "id", sv: 390, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k92", keyword: "berapa rakaat shalat tasbih", market: "id", sv: 390, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k93", keyword: "qiblah", market: "my", sv: 390, kd: 40, intent: null, behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null },
  { id: "k94", keyword: "islamic toys", market: "uk", sv: 390, kd: 5, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k95", keyword: "apa bacaan tasbih", market: "id", sv: 320, kd: 28, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k96", keyword: "how to perform salatul tasbih", market: "uk", sv: 320, kd: 9, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k97", keyword: "tata cara sholat tasbih", market: "sa", sv: 320, kd: 25, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k98", keyword: "islamic gift", market: "uk", sv: 320, kd: 35, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k99", keyword: "islamic gifts for women", market: "uk", sv: 320, kd: 3, intent: "Informational", behaviorIntent: "对比型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k100", keyword: "islamic gifts for wedding", market: "uk", sv: 320, kd: 4, intent: "Informational", behaviorIntent: "对比型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k101", keyword: "zikr ring", market: "us", sv: 320, kd: 11, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k102", keyword: "افضل شركة نقل عفش بتبوك", market: "sa", sv: 320, kd: 12, intent: null, behaviorIntent: "对比型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k103", keyword: "الخاتم الذكي", market: "sa", sv: 320, kd: 21, intent: null, behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "一级核心", questionType: null },
  { id: "k104", keyword: "what is dhikr", market: "uk", sv: 320, kd: 20, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k105", keyword: "what is dhikr", market: "us", sv: 320, kd: 11, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k106", keyword: "what is zikr ring", market: "us", sv: 320, kd: 11, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "一级核心", questionType: "what" },
  { id: "k107", keyword: "how to pray salatul tasbih", market: "uk", sv: 320, kd: 5, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k108", keyword: "how to pray salatul tasbih", market: "us", sv: 260, kd: 21, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k109", keyword: "islamic jewelry", market: "uk", sv: 260, kd: 11, intent: "Informational,Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k110", keyword: "salatul tasbih padhne ka tarika", market: "sa", sv: 260, kd: 23, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k111", keyword: "zikr ring", market: "de", sv: 260, kd: 14, intent: "Informational,Transactional", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k112", keyword: "what is the direction of kaaba", market: "uk", sv: 260, kd: 34, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: "what" },
  { id: "k113", keyword: "gift for islamic wedding", market: "uk", sv: 260, kd: 5, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null },
  { id: "k114", keyword: "prayer beads", market: "sa", sv: 260, kd: 14, intent: "Informational", behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k115", keyword: "solat sunat tasbih", market: "sa", sv: 260, kd: 13, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k116", keyword: "zikr ring", market: "tr", sv: 260, kd: 25, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k117", keyword: "what is slow living", market: "us", sv: 260, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k118", keyword: "gold name necklace", market: "sa", sv: 210, kd: 14, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k119", keyword: "how to pray salatul tasbih", market: "sa", sv: 210, kd: 14, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k120", keyword: "zikr", market: "my", sv: 210, kd: 24, intent: null, behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k121", keyword: "how to pray salatul tasbih namaz", market: "us", sv: 210, kd: 0, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k122", keyword: "arabic name necklace", market: "sa", sv: 210, kd: 17, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k123", keyword: "aqeeq ring", market: "sa", sv: 210, kd: 14, intent: null, behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "四级兜底", questionType: null },
  { id: "k124", keyword: "how to salatul tasbih prayer", market: "us", sv: 210, kd: 0, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k125", keyword: "how to read salatul tasbih", market: "us", sv: 210, kd: 7, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k126", keyword: "digital tasbeeh", market: "sa", sv: 210, kd: 26, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "一级核心", questionType: null },
  { id: "k127", keyword: "digital tasbih", market: "sa", sv: 210, kd: 26, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "一级核心", questionType: null },
  { id: "k128", keyword: "what is tasbih", market: "us", sv: 210, kd: 0, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k129", keyword: "how to pray salatul tasbih prayer", market: "us", sv: 210, kd: 2, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k130", keyword: "bracelet for girls", market: "sa", sv: 210, kd: 19, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null },
  { id: "k131", keyword: "how to do salatul tasbih", market: "us", sv: 210, kd: 16, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k132", keyword: "do a sholat tasbih", market: "id", sv: 170, kd: 22, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "do" },
  { id: "k133", keyword: "gift in islam", market: "ae", sv: 170, kd: 15, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null },
  { id: "k134", keyword: "how to do dhikr", market: "uk", sv: 170, kd: 27, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k135", keyword: "how to locate kaaba direction", market: "uk", sv: 170, kd: 27, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: "how" },
  { id: "k136", keyword: "which direction is kaaba", market: "us", sv: 170, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: "which" },
  { id: "k137", keyword: "what is a tasbih", market: "us", sv: 170, kd: 0, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k138", keyword: "misbaha", market: "sa", sv: 170, kd: 30, intent: "Informational", behaviorIntent: "混合型", pagePlanningIntent: "工具生态页", layer: "三级变体", questionType: null },
  { id: "k139", keyword: "bagaimana bacaan tasbih", market: "id", sv: 170, kd: 28, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k140", keyword: "how to pray salatul tasbih namaz", market: "uk", sv: 140, kd: 6, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k141", keyword: "how to do dhikr", market: "us", sv: 140, kd: 23, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k142", keyword: "how to perform salatul tasbih", market: "us", sv: 140, kd: 6, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k143", keyword: "how to pray salatul tasbih", market: "ae", sv: 140, kd: 12, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k144", keyword: "how to perform salatul tasbih", market: "ae", sv: 140, kd: 6, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k145", keyword: "what is tasbih", market: "uk", sv: 140, kd: 6, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k146", keyword: "apa itu shalat tasbih", market: "id", sv: 140, kd: 28, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k147", keyword: "berapa jumlah tasbih", market: "id", sv: 140, kd: 22, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k148", keyword: "does lively wallpaper slow down pc", market: "us", sv: 140, kd: 29, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "does" },
  { id: "k149", keyword: "what is a tasbih", market: "uk", sv: 110, kd: 2, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k150", keyword: "which direction is kaaba", market: "uk", sv: 110, kd: 30, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: "which" },
  { id: "k151", keyword: "what is dhikr in islam", market: "us", sv: 110, kd: 14, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "what" },
  { id: "k152", keyword: "apa itu bertasbih", market: "id", sv: 110, kd: 19, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k153", keyword: "how to read salatul tasbih", market: "uk", sv: 110, kd: 6, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "how" },
  { id: "k154", keyword: "kapan kalimat tasbih diucapkan", market: "id", sv: 110, kd: 23, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: "other" },
  { id: "k155", keyword: "what direction is the kaaba", market: "us", sv: 110, kd: 28, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: "what" },
  { id: "k156", keyword: "zikr ring price", market: "us", sv: 90, kd: 15, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "产品详情页", layer: "一级核心", questionType: null },
  { id: "k157", keyword: "how to use zikr ring", market: "us", sv: 90, kd: 14, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "一级核心", questionType: "how" },
  { id: "k158", keyword: "zikr ring", market: "au", sv: 90, kd: 2, intent: "Commercial", behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null },
  { id: "k159", keyword: "bagaimana bunyi kalimat tasbih", market: "id", sv: 70, kd: 21, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "四级兜底", questionType: "other" },
  { id: "k160", keyword: "how to make tasbih", market: "us", sv: 70, kd: 20, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "四级兜底", questionType: "how" },
  { id: "k161", keyword: "kapan waktu sholat tasbih", market: "id", sv: 70, kd: 24, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "四级兜底", questionType: "other" },
  { id: "k162", keyword: "black zikr ring", market: "us", sv: 50, kd: 9, intent: "Informational", behaviorIntent: "行动型", pagePlanningIntent: "产品详情页", layer: "一级核心", questionType: null },
  { id: "k163", keyword: "how to embrace slow living", market: "us", sv: 40, kd: 12, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "四级兜底", questionType: "how" },
  { id: "k164", keyword: "berapa kali membaca tasbih nabi yunus", market: "id", sv: 40, kd: 19, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "四级兜底", questionType: "other" },
  { id: "k165", keyword: "what should your night skincare routine be", market: "us", sv: 40, kd: 14, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "四级兜底", questionType: "what" },
  { id: "k166", keyword: "bagaimana bunyi bacaan tasbih", market: "id", sv: 40, kd: 23, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "三级变体", questionType: "other" },
  { id: "k167", keyword: "does zikr ring vibrate", market: "us", sv: 40, kd: 9, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "一级核心", questionType: "does" },
  { id: "k168", keyword: "which serum is best for night routine", market: "us", sv: 30, kd: 17, intent: "Commercial", behaviorIntent: "对比型", pagePlanningIntent: "场景使用页", layer: "四级兜底", questionType: "which" },
  { id: "k169", keyword: "are zikr rings halal", market: "us", sv: 30, kd: 8, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "一级核心", questionType: "are" },
  { id: "k170", keyword: "weslamic order tracking", market: null, sv: null, kd: null, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "一级核心", questionType: null },
  { id: "k171", keyword: "weslamic customer service", market: null, sv: null, kd: null, intent: null, behaviorIntent: "官网导航", pagePlanningIntent: "品牌主页", layer: "一级核心", questionType: null },
  { id: "k172", keyword: "weslamic login", market: null, sv: null, kd: null, intent: null, behaviorIntent: "官网导航", pagePlanningIntent: "品牌主页", layer: "一级核心", questionType: null },
  { id: "k173", keyword: "weslamic.com", market: null, sv: null, kd: null, intent: null, behaviorIntent: "官网导航", pagePlanningIntent: "品牌主页", layer: "一级核心", questionType: null },
  { id: "k174", keyword: "weslamic official", market: null, sv: null, kd: null, intent: null, behaviorIntent: "官网导航", pagePlanningIntent: "品牌主页", layer: "一级核心", questionType: null },
  { id: "k175", keyword: "weslamic", market: null, sv: null, kd: null, intent: null, behaviorIntent: "官网导航", pagePlanningIntent: "品牌主页", layer: "一级核心", questionType: null },

  // ── demo · Tasbih 念珠主题演示词（非真实 176 词，仅用于 Loom Grid v2 喂厚数据）─────
  { id: "d0", keyword: "tasbih beads", market: "us", sv: 1600, kd: 20, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "一级核心", questionType: null }, // demo
  { id: "d1", keyword: "prayer beads tasbih", market: "uk", sv: 590, kd: 18, intent: "Commercial", behaviorIntent: "混合型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null }, // demo
  { id: "d2", keyword: "tasbih necklace", market: "us", sv: 320, kd: 15, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null }, // demo
  { id: "d3", keyword: "wood tasbih", market: "us", sv: 480, kd: 12, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null }, // demo
  { id: "d4", keyword: "wooden prayer beads", market: "uk", sv: 320, kd: 14, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null }, // demo
  { id: "d5", keyword: "gemstone tasbih", market: "sa", sv: 390, kd: 16, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null }, // demo
  { id: "d6", keyword: "tasbih gift", market: "uk", sv: 480, kd: 10, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null }, // demo
  { id: "d7", keyword: "tasbih gift set", market: "us", sv: 260, kd: 8, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null }, // demo
  { id: "d8", keyword: "ramadan tasbih", market: "uk", sv: 590, kd: 12, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null }, // demo
  { id: "d9", keyword: "eid tasbih", market: "uk", sv: 320, kd: 10, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null }, // demo
  { id: "d10", keyword: "digital tasbih counter", market: "my", sv: 720, kd: 22, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "二级独立", questionType: null }, // demo
  { id: "d11", keyword: "electronic tasbih", market: "sa", sv: 210, kd: 18, intent: null, behaviorIntent: "行动型", pagePlanningIntent: "工具生态页", layer: "三级变体", questionType: null }, // demo
  { id: "d12", keyword: "tasbih dhikr", market: "us", sv: 210, kd: 14, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "二级独立", questionType: null }, // demo
  { id: "d13", keyword: "how to use tasbih for dhikr", market: "uk", sv: 170, kd: 12, intent: "Informational", behaviorIntent: "了解型", pagePlanningIntent: "知识深度页", layer: "三级变体", questionType: "how" }, // demo
  { id: "d14", keyword: "islamic jewelry gift", market: "uk", sv: 390, kd: 15, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null }, // demo
  { id: "d15", keyword: "muslim jewelry", market: "us", sv: 480, kd: 18, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null }, // demo
  { id: "d16", keyword: "zikr ring gift", market: "uk", sv: 170, kd: 8, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "场景使用页", layer: "二级独立", questionType: null }, // demo
  { id: "d17", keyword: "islamic necklace", market: "us", sv: 320, kd: 14, intent: "Commercial", behaviorIntent: "行动型", pagePlanningIntent: "品类聚合页", layer: "二级独立", questionType: null }, // demo
];
